fix: added missing onSubscriptionResult argument
zino-hofmann/graphql-flutter pull request #1312
Opened 2023-03-31 21:14 UTC by PhilippS93

SubscriptionOnClient was missing the SubscriptionOnClient constructor param

Describe the purpose of the pull request.

2023-03-31 23:02 UTC, vincenzopalazzo commented
thanks, could you add the scope in the commit header? like `fix(graphql_flutter): added missing onSubscriptionResult argument`

2023-04-01 06:51 UTC, PhilippS93 commented
alright, done!

2023-04-01 08:24 UTC, vincenzopalazzo requested changes

2023-04-01 08:24 UTC, vincenzopalazzo commented on packages/graphql_flutter/lib/src/widgets/subscription.dart
> +    final client = useGraphQLClient();
```suggestion
    final client = useGraphQLClient();
```

looks like that the space is not needed?

2023-04-02 09:32 UTC, vincenzopalazzo commented
ok, now the last thing is squash the commit in a single one, 3 commits for a single line of code change is to much sorry!

2023-04-03 08:28 UTC, PhilippS93 commented
@vincenzopalazzo , when you accept the PR, you can select "Squash and Merge". This should solve the problem, doesn´t it?

2023-04-03 09:53 UTC, vincenzopalazzo commented
@PhilippS93 does not work in this way, sorry!

2023-04-03 16:23 UTC, PhilippS93 commented
No problem, i squashed the commits :)

2023-04-03 16:25 UTC, vincenzopalazzo approved these changes

2023-04-03 16:37 UTC, merged