docs: upgraded connectivity_plus package
zino-hofmann/graphql-flutter pull request #1424
Opened 2024-04-12 11:11 UTC by Avinash-dhiraj

There are some simple steps to get your PR merged, that are the following:

- As app store introduced mandatory privacy manifest files for some of packages being used in the application. connectivity_plus 6.0.2 is one of them and current version of connectivity_plus 6.0.2 has added support for privacy manifest but graphql_flutter still using connectivity_plus 5.0.0 which leads into compatibility issue. App store is very specific about the deadline of these as well which is 1st of may.;

upgraded connectivity_plus from 5.0.0 to 6.0.2

Please merge this on priority as this breaking changes is needed for all the flutter application which is using connectivity_plus 6.0.2 along with graphql_flutter

2024-04-12 21:29 UTC, vincenzopalazzo commented
looks like that needs a rebase, please ping me when the conflict are fixed

2024-04-13 02:03 UTC, Avinash-dhiraj commented
> looks like that needs a rebase, please ping me when the conflict are fixed

there is one conflict in pubspec file 
```
<<<<<<< connectivity-plus-upgrade
  connectivity_plus: ^6.0.2
=======
  connectivity_plus: ^5.0.0
>>>>>>> main
```
which can be resolved when someone merge it.

2024-04-13 11:17 UTC, vincenzopalazzo requested changes
We do not use merge commit inside the PR, so you should rebase it with `git rebase`.

This commit can be removed dee9b9414b8ae275b541174aaeaa61ff39744d70

In addition I left a couple of comments because I am a little bit confused while looking at your commit history

2024-04-13 11:17 UTC, vincenzopalazzo commented on packages/graphql_flutter/lib/src/widgets/hooks/subscription.dart
> -  ConnectivityResult? _currentConnectivityResult;
this commit header should start with `fix(graphel_flutter):`

2024-04-13 11:17 UTC, vincenzopalazzo commented on packages/graphql_flutter/pubspec.yaml
> +  #connectivity_plus: ^5.0.0
not sure what you want to do with this commit, but I think this should be folded in the previous one

2024-04-13 11:17 UTC, vincenzopalazzo commented on packages/graphql_flutter/pubspec.yaml
> -  #connectivity_plus: ^5.0.0
same, it need to be folded with the previous one

2024-04-25 11:19 UTC, johnmartel commented
@vincenzopalazzo any chance of getting this merged and released quickly if I fork this PR and submit an updated version? This is creating an unnecessary roadblock for projects that use both `graphql_flutter` and `connectivity_plus` that want to upgrade their dependencies.

2024-05-03 10:01 UTC, selawik commented
Any updates?

2024-05-08 18:17 UTC, SachinCodeMatrix commented
@Avinash-dhiraj @vincenzopalazzo  please check this

2024-05-16 08:01 UTC, vincenzopalazzo commented
This is unresolved https://github.com/zino-hofmann/graphql-flutter/pull/1424#pullrequestreview-1999240159

I have nothing to check

2024-09-11 09:39 UTC, vincenzopalazzo commented
Closing because looks like that there is already a fix https://github.com/zino-hofmann/graphql-flutter/issues/1423#issuecomment-2134515753

Please open a new PR with a good git history if the problem persit

2024-09-11 09:39 UTC, closed without merging