Fix websocket disconnect after connection loss
zino-hofmann/graphql-flutter pull request #963
Opened 2021-09-18 19:24 UTC by Bligoubloups

Changes requested for #888
Fix #856

`platform_stub.dart` was unused as well as `isHtml` and `isIo` booleans.

2021-12-19 07:14 UTC, vincenzopalazzo commented
HI.

I'm scheduler to review this before the end of the year, can you rebase this PR on master? I like how you managed the export package for each platform.

2021-12-19 09:43 UTC, kateile commented
@vincenzopalazzo hi, any progress on this?

2021-12-19 12:28 UTC, Bligoubloups commented
Hello @vincenzopalazzo I'm already up to date with master. Did you mean rebase on beta ?

2021-12-19 13:11 UTC, vincenzopalazzo commented
>Hello @vincenzopalazzo I'm already up to date with master. Did you mean rebase on beta ?

Yep!

2021-12-24 17:54 UTC, vincenzopalazzo requested changes
LGTM, but I have only one change request for code style.

Thanks for your work.

2021-12-24 17:54 UTC, vincenzopalazzo commented on packages/graphql/lib/src/links/websocket_link/websocket_client.dart
> +          (await config.connect(Uri.parse(url), protocols)).forGraphQL();
```
var connection = await config.connect(Uri.parse(url), protocols)
suggestion = connection.forGraphQL();
```

This is a more clean way to write the same code, but it is more accessible for people people with disabilities

2021-12-24 19:37 UTC, vytautas-pranskunas- commented
Watching

2021-12-27 13:31 UTC, vincenzopalazzo approved these changes

2021-12-27 13:31 UTC, merged